### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by SzotsGabor** [JoAnnP38/Pedantic#5]
I installed Pedantic 0.2 under the Cute Chess GUI but when I wanted to start a game CC said it could not initialize the engine.

Then I installed it under Arena. When I started the engine Arena issued this message: Fatal error occurred in Pedantic: 'Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).'.
Interestingly, when I restarted the engine the above message did not appear and I could play a game.

**Comment by JoAnnP38** [comment]
Inside the zip file there should be a zip file (i.e. pedantic.json) that contains the weights to be used by the evaluation function. In theory, it should recreate this if missing. I'll look into that. Did you copy the .json file into the installation folder?

**Comment by SzotsGabor** [comment]
Yes, it is there. But currently it is different from what the zip file contains. I don' know why, I copied all zip contents to the installation folder at the time of extracting the zip file so it was there before I first started the engine.
Should I make the evaluationID parameter equal with this file? I have not done so yet.

**Comment by JoAnnP38** [comment]
Okay, I actually was able to recreate your error in the Cute Chess GUI. Here's the problem. On the advanced tab for the Pedantic engine, you will see a parameter named "Evaluation_ID" that has a default value of "<empty>". Pedantic does not expect "<empty>" to be passed as an Evaluation ID (it expects a GUID.) Arena never passes this back since it is the default value and doesn't resend default. You can work around this error by blacking out the Evaluation_ID setting on the cute chess engine advanced tab.

**Comment by JoAnnP38** [comment]
Okay, I actually was able to recreate your error in the Cute Chess GUI. Here's the problem. On the advanced tab for the Pedantic engine, you will see a parameter named "Evaluation_ID" that has a default value of "<empty>". Pedantic does not expect "<empty>" to be passed as an Evaluation ID (it expects a GUID.) Arena never passes this back since it is the default value and doesn't resend default. You can work around this error by blacking out the Evaluation_ID setting on the cute chess engine advanced tab.

**Comment by JoAnnP38** [comment]
> Yes, it is there. But currently it is different from what the zip file contains. I don' know why, I copied all zip contents to the installation folder at the time of extracting the zip file so it was there before I first started the engine. Should I make the evaluationID parameter equal with this file? I have not done so yet.

No, you should not have to manipulate Evaluation_ID at all other than just blank it out in the GUI settings. BTW, whenever the JSON file is recreated, the ID is set to a random GUID value, so it will change when regenerated.

**Comment by JoAnnP38** [comment]
I am going to correct his issue by handling "<Empty>" whenever it is passed as the evaluation ID to the engine by simply ignoring it instead of trying to parse it. Sorry about that. I will update the binaries in the 0.2 release when this is corrected.

**Comment by SzotsGabor** [comment]
I have blanked it out and now it works. Thank you for the help.
